"""
Stage 5 — Infra Generator
---------------------------
Generates docker-compose, .env.example, README, startup scripts.
No LLM needed for most of this — pure template generation.
"""

import json
from backend.llm.ollama_client import ask_coder, parse_json_response


def generate_env_example(plan: dict) -> str:
    db_type = plan["tech_stack"]["database"]["type"]
    lines = [
        "# Environment Variables",
        "# Copy this to .env and fill in values",
        "",
        "# App",
        "SECRET_KEY=your-secret-key-change-in-production",
        "DEBUG=true",
        "",
    ]

    if db_type == "sqlite":
        lines += [
            "# Database (SQLite)",
            "DATABASE_URL=sqlite:///./app.db",
            "",
        ]
    else:
        lines += [
            "# Database (PostgreSQL)",
            "DATABASE_URL=postgresql://user:password@localhost:5432/appdb",
            "POSTGRES_USER=user",
            "POSTGRES_PASSWORD=password",
            "POSTGRES_DB=appdb",
            "",
        ]

    lines += [
        "# JWT",
        "JWT_SECRET_KEY=your-jwt-secret-key",
        "JWT_ALGORITHM=HS256",
        "ACCESS_TOKEN_EXPIRE_MINUTES=30",
        "",
        "# Frontend",
        "VITE_API_URL=http://localhost:8000",
    ]

    return "\n".join(lines)


def generate_docker_compose(plan: dict) -> str:
    db_type = plan["tech_stack"]["database"]["type"]
    prompt = plan["prompt"]

    services = """version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
"""

    if db_type == "postgresql":
        services += """      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
"""
    else:
        services += """      - []

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
"""

    return services


def generate_backend_dockerfile() -> str:
    return """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""


def generate_frontend_dockerfile() -> str:
    return """FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
"""


def generate_readme(plan: dict, db_result: dict, backend_result: dict, frontend_result: dict) -> str:
    prompt = plan["prompt"]
    db_type = plan["tech_stack"]["database"]["type"]
    tables = db_result.get("tables", [])
    endpoints = backend_result.get("api_spec", {}).get("endpoints", [])
    pages = frontend_result.get("pages", [])

    endpoint_list = "\n".join([
        f"- `{ep.get('method')} {ep.get('path')}` — {ep.get('description', '')}"
        for ep in endpoints[:10]  # show first 10
    ])

    return f"""# Generated App

> {prompt}

## Tech Stack

- **Frontend**: React + TailwindCSS + Vite
- **Backend**: FastAPI (Python)
- **Database**: {db_type.upper()}
- **Auth**: JWT

## Quick Start

### Development (no Docker)

**Backend:**
```bash
cd backend
pip install -r requirements.txt
cp ../.env.example ../.env
uvicorn main:app --reload --port 8000
```

**Frontend:**
```bash
cd frontend
npm install
npm run dev
```

Open http://localhost:5173

### With Docker
```bash
cp .env.example .env
docker-compose up --build
```

## Database Tables
{chr(10).join([f'- {t}' for t in tables])}

## API Endpoints
{endpoint_list}

## Pages
{chr(10).join([f'- {p}' for p in pages])}

---
*Generated by OffRepl — Offline AI Project Generator*
"""


def generate_startup_script() -> str:
    return """#!/bin/bash
# Quick start script — runs without Docker

echo "Starting backend..."
cd backend
pip install -r requirements.txt -q
uvicorn main:app --reload --port 8000 &
BACKEND_PID=$!

echo "Starting frontend..."
cd ../frontend
npm install --silent
npm run dev &
FRONTEND_PID=$!

echo ""
echo "App running!"
echo "  Frontend: http://localhost:5173"
echo "  Backend:  http://localhost:8000"
echo "  API docs: http://localhost:8000/docs"
echo ""
echo "Press Ctrl+C to stop"

trap "kill $BACKEND_PID $FRONTEND_PID" EXIT
wait
"""


async def generate_infra(plan: dict, db_result: dict, backend_result: dict, frontend_result: dict, websocket=None) -> dict:
    """Generate all infrastructure files."""

    async def emit(event: str, message: str):
        if websocket:
            await websocket.send_json({"event": event, "message": message})

    await emit("stage", "Generating infrastructure files...")

    files = [
        {
            "path": "docker-compose.yml",
            "content": generate_docker_compose(plan)
        },
        {
            "path": ".env.example",
            "content": generate_env_example(plan)
        },
        {
            "path": "backend/Dockerfile",
            "content": generate_backend_dockerfile()
        },
        {
            "path": "frontend/Dockerfile",
            "content": generate_frontend_dockerfile()
        },
        {
            "path": "README.md",
            "content": generate_readme(plan, db_result, backend_result, frontend_result)
        },
        {
            "path": "start.sh",
            "content": generate_startup_script()
        }
    ]

    await emit("stage", f"Infra generated — {len(files)} files")

    return {"files": files}
